[[redirects]]
  from = "/slack"
  to = "https://join.slack.com/t/lowellbytelab/shared_invite/enQtNDI4MTcyMTE5MjM2LWIyOWFkYmRjZGNkODhkNWRhMzY0MDY4NDI5YTg4OTA2M2I4NjBlNDNhNTY1MzFkNGZjY2E4ZTQyOTBmMGY4NGM"
  status = 302
  force = true
